#!/bin/bash
# BigBrotherAnalytics Build Script
# Generated by Claude Code

set -e  # Exit on error
set -x  # Print commands

echo "=== Building BigBrotherAnalytics ==="
echo "Working directory: $(pwd)"

# Navigate to build directory
cd /home/muyiwa/Development/BigBrotherAnalytics/build

# Set environment variables
export CC=/home/linuxbrew/.linuxbrew/bin/clang
export CXX=/home/linuxbrew/.linuxbrew/bin/clang++
export LD_LIBRARY_PATH=/home/linuxbrew/.linuxbrew/Cellar/llvm/21.1.5/lib/x86_64-unknown-linux-gnu:/usr/local/lib:$LD_LIBRARY_PATH

# Build with ninja
echo "=== Running ninja build ==="
ninja -j 4

# Check if build succeeded
if [ $? -eq 0 ]; then
    echo "=== Build completed successfully! ==="
    echo "Executables:"
    ls -lh bin/
    echo ""
    echo "Libraries:"
    ls -lh lib/
else
    echo "=== Build failed! ==="
    exit 1
fi
