#pragma once

#include "../utils/types.hpp"
#include "../correlation_engine/options_pricing.hpp"
#include "../correlation_engine/correlation.hpp"
#include "../risk_management/risk_manager.hpp"
#include "../schwab_api/schwab_client.hpp"

#include <vector>
#include <memory>
#include <string>
#include <unordered_map>
#include <chrono>

namespace bigbrother::strategy {

using namespace types;

/**
 * Trading Signal
 *
 * Generated by strategies to indicate trading opportunities
 */
struct TradingSignal {
    std::string strategy_name;
    std::string symbol;
    SignalType type;                    // Buy, Sell, Hold, CloseAll
    double confidence;                  // 0.0 to 1.0
    double expected_return;             // Expected return in dollars
    double max_risk;                    // Maximum risk in dollars
    double win_probability;             // Probability of profit
    Timestamp timestamp;
    std::string rationale;              // Human-readable explanation
    std::vector<std::string> features;  // Key features driving signal

    // Options-specific fields
    std::optional<options::OptionContract> option_contract;
    std::optional<options::Greeks> greeks;
    std::optional<double> implied_volatility;

    [[nodiscard]] auto isActionable() const noexcept -> bool {
        return type != SignalType::Hold &&
               confidence > 0.6 &&
               expected_return > 50.0 &&      // Min $50 expected value per PRD
               win_probability > 0.60;         // Min 60% win rate per PRD
    }

    [[nodiscard]] auto riskRewardRatio() const noexcept -> double {
        if (max_risk == 0.0) return 0.0;
        return expected_return / max_risk;
    }
};

/**
 * Strategy Context
 *
 * Provides all data needed for strategy execution
 */
struct StrategyContext {
    // Market data
    std::unordered_map<std::string, Quote> current_quotes;
    std::unordered_map<std::string, std::vector<Bar>> historical_bars;
    std::unordered_map<std::string, schwab::OptionsChainData> options_chains;

    // Correlation data
    std::shared_ptr<correlation::CorrelationMatrix> correlation_matrix;
    std::vector<correlation::CorrelationSignalGenerator::CorrelationSignal> correlation_signals;

    // Portfolio state
    std::vector<Position> current_positions;
    risk::PortfolioRisk portfolio_risk;

    // Account info
    double account_value;
    double available_capital;

    // Market conditions
    double vix;                         // Volatility index
    double market_sentiment;            // -1 (fear) to +1 (greed)

    // Timestamp
    Timestamp current_time;
};

/**
 * Base Strategy Interface
 *
 * All trading strategies inherit from this.
 */
class IStrategy {
public:
    virtual ~IStrategy() = default;

    /**
     * Generate trading signals
     *
     * @param context Market context and data
     * @return Vector of trading signals
     */
    [[nodiscard]] virtual auto generateSignals(StrategyContext const& context)
        -> std::vector<TradingSignal> = 0;

    /**
     * Get strategy name
     */
    [[nodiscard]] virtual auto getName() const noexcept -> std::string = 0;

    /**
     * Get strategy description
     */
    [[nodiscard]] virtual auto getDescription() const noexcept -> std::string = 0;

    /**
     * Check if strategy is active
     */
    [[nodiscard]] virtual auto isActive() const noexcept -> bool = 0;

    /**
     * Enable/disable strategy
     */
    virtual auto setActive(bool active) -> void = 0;

    /**
     * Get strategy parameters
     */
    [[nodiscard]] virtual auto getParameters() const
        -> std::unordered_map<std::string, std::string> = 0;
};

/**
 * Base Strategy Implementation
 *
 * Provides common functionality for all strategies
 */
class BaseStrategy : public IStrategy {
public:
    explicit BaseStrategy(std::string name, std::string description)
        : name_{std::move(name)},
          description_{std::move(description)},
          active_{true} {}

    [[nodiscard]] auto getName() const noexcept -> std::string override {
        return name_;
    }

    [[nodiscard]] auto getDescription() const noexcept -> std::string override {
        return description_;
    }

    [[nodiscard]] auto isActive() const noexcept -> bool override {
        return active_;
    }

    auto setActive(bool active) -> void override {
        active_ = active;
    }

protected:
    /**
     * Helper: Check if VIX indicates high volatility environment
     */
    [[nodiscard]] auto isHighVolatilityRegime(double vix) const noexcept -> bool {
        return vix > 25.0;  // VIX > 25 indicates elevated volatility
    }

    /**
     * Helper: Check if market is in fear (good for option buyers)
     */
    [[nodiscard]] auto isMarketInFear(double vix, double sentiment) const noexcept -> bool {
        return vix > 30.0 || sentiment < -0.5;
    }

    /**
     * Helper: Check if option is near expiration
     */
    [[nodiscard]] auto isNearExpiration(
        options::OptionContract const& contract,
        Timestamp current_time
    ) const noexcept -> bool {
        return contract.daysToExpiration(current_time) < 7.0;
    }

    std::string name_;
    std::string description_;
    bool active_;
};

} // namespace bigbrother::strategy
