-- Trading Signals Tracking Schema
-- Captures every signal generated by the trading engine for analysis and reporting

CREATE TABLE IF NOT EXISTS trading_signals (
    signal_id VARCHAR PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    strategy VARCHAR NOT NULL,
    symbol VARCHAR NOT NULL,
    signal_type VARCHAR, -- BUY, SELL, HOLD, CLOSE
    confidence DOUBLE,
    expected_return DOUBLE,
    win_probability DOUBLE,
    estimated_cost DOUBLE,
    max_risk DOUBLE,
    status VARCHAR NOT NULL, -- GENERATED, FILTERED_CONFIDENCE, FILTERED_RETURN, FILTERED_WIN_PROB, FILTERED_BUDGET, REJECTED_RISK, EXECUTED, FAILED
    rejection_reason VARCHAR,
    order_ids VARCHAR,
    greeks_delta DOUBLE,
    greeks_gamma DOUBLE,
    greeks_theta DOUBLE,
    greeks_vega DOUBLE,
    greeks_rho DOUBLE,
    iv_percentile DOUBLE,
    days_to_expiration INTEGER,
    underlying_price DOUBLE,
    strike_price DOUBLE,
    market_conditions JSON
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON trading_signals(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signals_status ON trading_signals(status);
CREATE INDEX IF NOT EXISTS idx_signals_strategy ON trading_signals(strategy);
CREATE INDEX IF NOT EXISTS idx_signals_symbol ON trading_signals(symbol);
CREATE INDEX IF NOT EXISTS idx_signals_date ON trading_signals(DATE(timestamp));

-- View: Today's signals
CREATE OR REPLACE VIEW v_signals_today AS
SELECT * FROM trading_signals
WHERE DATE(timestamp) = CURRENT_DATE
ORDER BY timestamp DESC;

-- View: Rejection analysis (today)
CREATE OR REPLACE VIEW v_rejection_analysis_today AS
SELECT
    status,
    COUNT(*) as count,
    AVG(confidence) as avg_confidence,
    AVG(expected_return) as avg_expected_return,
    AVG(estimated_cost) as avg_cost,
    SUM(expected_return) as total_missed_return
FROM trading_signals
WHERE DATE(timestamp) = CURRENT_DATE
AND status != 'EXECUTED'
GROUP BY status
ORDER BY count DESC;

-- View: Signal acceptance rate by strategy
CREATE OR REPLACE VIEW v_signal_acceptance_by_strategy AS
SELECT
    strategy,
    DATE(timestamp) as date,
    COUNT(*) as total_signals,
    COUNT(CASE WHEN status = 'EXECUTED' THEN 1 END) as executed,
    COUNT(CASE WHEN status != 'EXECUTED' THEN 1 END) as rejected,
    CAST(COUNT(CASE WHEN status = 'EXECUTED' THEN 1 END) AS DOUBLE) / COUNT(*) * 100 as acceptance_rate
FROM trading_signals
GROUP BY strategy, DATE(timestamp)
ORDER BY date DESC, acceptance_rate DESC;

-- View: Budget-rejected signals analysis
CREATE OR REPLACE VIEW v_budget_rejected_signals AS
SELECT
    DATE(timestamp) as date,
    strategy,
    symbol,
    estimated_cost,
    expected_return,
    confidence,
    win_probability
FROM trading_signals
WHERE status = 'FILTERED_BUDGET'
ORDER BY timestamp DESC;

-- View: Daily signal summary
CREATE OR REPLACE VIEW v_daily_signal_summary AS
SELECT
    DATE(timestamp) as date,
    COUNT(*) as total_signals,
    COUNT(CASE WHEN status = 'EXECUTED' THEN 1 END) as executed,
    COUNT(CASE WHEN status = 'FILTERED_BUDGET' THEN 1 END) as budget_rejected,
    COUNT(CASE WHEN status = 'FILTERED_CONFIDENCE' THEN 1 END) as confidence_rejected,
    COUNT(CASE WHEN status = 'FILTERED_RETURN' THEN 1 END) as return_rejected,
    COUNT(CASE WHEN status = 'REJECTED_RISK' THEN 1 END) as risk_rejected,
    AVG(expected_return) as avg_expected_return,
    SUM(CASE WHEN status = 'EXECUTED' THEN expected_return ELSE 0 END) as executed_return_potential,
    SUM(CASE WHEN status != 'EXECUTED' THEN expected_return ELSE 0 END) as missed_return_potential
FROM trading_signals
GROUP BY DATE(timestamp)
ORDER BY date DESC;
