/**
 * Auto-generated model weights metadata
 * Generated by: scripts/ml/export_model_weights_to_cpp.py
 * Source model: price_predictor_best.pth
 * Date: 2025-11-13T18:59:01
 */

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace bigbrother::ml {

// Model architecture
struct ModelArchitecture {
    // Layer dimensions (inferred from weights)
    
    // Total parameters
    static constexpr int total_params = 58947;
};

// Weight file paths (relative to models/ directory)
struct WeightFiles {
    static constexpr std::string_view network_0_bias = "weights/network_0_bias.bin";
    static constexpr std::string_view network_0_weight = "weights/network_0_weight.bin";
    static constexpr std::string_view network_12_bias = "weights/network_12_bias.bin";
    static constexpr std::string_view network_12_weight = "weights/network_12_weight.bin";
    static constexpr std::string_view network_3_bias = "weights/network_3_bias.bin";
    static constexpr std::string_view network_3_weight = "weights/network_3_weight.bin";
    static constexpr std::string_view network_6_bias = "weights/network_6_bias.bin";
    static constexpr std::string_view network_6_weight = "weights/network_6_weight.bin";
    static constexpr std::string_view network_9_bias = "weights/network_9_bias.bin";
    static constexpr std::string_view network_9_weight = "weights/network_9_weight.bin";
};

// Normalization parameters (StandardScaler)
struct NormalizationParams {
    static constexpr int num_features = 60;  // Update this manually
    static constexpr std::string_view mean_file = "";
    static constexpr std::string_view std_file = "";
    // NOTE: Scaler parameters not found! Model may not work correctly.
};

}  // namespace bigbrother::ml
